name: giggle
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_animate: ^4.5.1
  camera: ^0.10.5+9
  video_player: ^2.8.5
  ar_flutter_plugin: ^0.7.3
  arcore_flutter_plugin: ^0.1.0
  firebase_core: ^2.27.0
  flutter_archive: ^6.0.3
  path_provider: ^2.1.4
  flutter_tts: ^4.0.2
  model_viewer_plus: ^1.7.2
  speech_to_text: ^6.6.0
  flutter_dotenv: ^5.2.1
  http: ^1.2.0
  logger: ^2.5.0
  web_socket_channel: ^2.4.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^4.15.8
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.1
  permission_handler: ^10.4.5
  audioplayers: ^5.2.1
  record: ^5.0.5
  lottie: ^3.1.3
  http_parser: ^4.0.2
  firebase_database: ^10.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/booze.png
    - assets/3d_models/numbers/number_0.glb
    - assets/3d_models/numbers/number_1.glb
    - assets/3d_models/numbers/number_2.glb
    - assets/3d_models/numbers/number_3.glb
    - assets/3d_models/numbers/number_4.glb
    - assets/3d_models/numbers/number_5.glb
    - assets/3d_models/numbers/number_6.glb
    - assets/3d_models/numbers/number_7.glb
    - assets/3d_models/numbers/number_8.glb
    - assets/3d_models/numbers/number_9.glb
    - assets/3d_models/chin_chest.glb
    - assets/3d_models/tpose.glb
    - assets/3d_models/square_picnic_table.glb
    - assets/3d_models/knees_stretch.glb
    - assets/3d_models/green_cube.glb
    - assets/3d_models/blue_cube.glb
    - assets/3d_models/cube.glb
    - assets/3d_models/A.glb
    - assets/3d_models/apple.glb
    - assets/3d_models/orange.glb
    - assets/3d_models/animated_a.fbx
    - assets/3d_models/animated_a.glb
    - assets/videos/Procedural_Dyscalculia_Division.mp4
    - assets/videos/Procedural_Dyscalculia_Subtraction.mp4
    - assets/videos/Procedural_Dyscalculia_Addition.mp4
    - assets/videos/Procedural_Dyscalculia_Multiplication.mp4
    - assets/videos/Verbal_Dyscalculia_Multiplication.mp4
    - assets/videos/Verbal_Dyscalculia_Addition.mp4
    - assets/videos/Verbal_Dyscalculia_Division.mp4
    - assets/videos/Verbal_Dyscalculia_Subtraction.mp4
    - assets/videos/Semantic_Dyscalculia_Subtraction.mp4
    - assets/videos/Semantic_Dyscalculia_Multiplication.mp4
    - assets/videos/Semantic_Dyscalculia_Addition.mp4
    - assets/videos/Semantic_Dyscalculia_Division.mp4

    - lib/config/.env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
