// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjNe1DtfE-A8KCFePKIS7IoK5d3H4X6c',
    appId: '1:516941991696:android:5fb813bf5487777c589f95',
    messagingSenderId: '516941991696',
    projectId: 'giggle-67ef5',
    databaseURL: 'https://giggle-67ef5-default-rtdb.firebaseio.com',
    storageBucket: 'giggle-67ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6N49QmZJ2n0-pPg9Lh4CMChQHOlYzWXM',
    appId: '1:516941991696:ios:42c061424e90a04b589f95',
    messagingSenderId: '516941991696',
    projectId: 'giggle-67ef5',
    databaseURL: 'https://giggle-67ef5-default-rtdb.firebaseio.com',
    storageBucket: 'giggle-67ef5.firebasestorage.app',
    androidClientId: '516941991696-2vti3dgpjatprl8v4hrk4t3edgd2vj5f.apps.googleusercontent.com',
    iosClientId: '516941991696-q09ekbdojnr1f724sv94e9nbmodoj3r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.giggle',
  );
}
